services:
  flight-api:
    build: .
    container_name: flight-api
    env_file: .env
    ports:
      - "0.0.0.0:3011:3011"
    restart: unless-stopped
    networks:
      - flight-network

networks:
  flight-network:
    name: flight-network
    driver: bridge
